### PR TITLE
Surpress warning messages when needed

### PR DESCRIPTION
**Pull request by liangxin1300**
Hi @krig ,

I want to add `warn_message` option, which default value is `True`, means if this option is `False`,
warning message
```
message = ('Warning: do not enter your password if anyone else has'
                   ' superuser privileges or access to your account.')
```
will not be shown when asking for a password.
What do you think about this?

Regards,
xin

### CODE REVIEW

**Comment by krig** [comment]
Is the message causing problems?

**Comment by liangxin1300** [comment]
@krig no problem, just comparing to ssh command, when need password, it has no other messages

**Comment by krig** [comment]
Yeah it does seem a bit excessive to me as well. OK, lets merge this :)

**Comment by liangxin1300** [comment]
Thanks @krig 
BTW, is there any way to input the password just once, when using parallax several times, like:
```
askpass = True
parallax.call()
...
parallax.copy()
...
parallax.slurp()
```
Or like above case, user must have to input password three times?

**Comment by krig** [comment]
hm, I thought it did cache the password, but to be honest I don't quite remember.

**Comment by liangxin1300** [comment]
From my experiment results, each time when using parallx should input password, when need ask for password. I can not grep any 'cache'(password) related codes.

**Pull request merged**
